os: linux
version: 0.0
files:
- source: /
  destination: /data/todoapp/
permissions:
  - object: /data
    type:
      - file
      - directory
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: hooks/after_install.sh
      runas: ec2-user
#  ApplicationStop:
#  - location: hooks/stop.sh
#    runas: root
#  ApplicationStart:
#  - location: hooks/start.sh
#    runas: root
