os: linux
version: 0.0
files:
- source: /
  destination: /data/todoapp/
permissions:
  - object: /data
    type:
      - file
      - directory
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: hooks/stop.sh
      runas: root
  BeforeInstall:
    - location: hooks/before_install.sh
      runas: root
  AfterInstall:
    - location: hooks/after_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: hooks/start.sh
      runas: ec2-user
