os: linux
version: 0.0
files:
- source: /
  destination: /data/todoapp/
hooks:
  AfterInstall:
    - location: hooks/after_install.sh
      runas: root
#  ApplicationStop:
#  - location: hooks/stop.sh
#    runas: root
#  ApplicationStart:
#  - location: hooks/start.sh
#    runas: root
