version: '3.1'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./initdb/:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"